services:
  postgres-ordering:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
      - ./docker/postgres/dumps/:/tmp/
    ports:
      - "5434:5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: "postgresOrdering"
      POSTGRES_USER: "postgresOrdering"
      POSTGRES_PASSWORD: "postgresOrdering"
    restart: always
volumes:
  database:
    driver: local